### ISSUE TITLE
Update import to const from let

### ISSUE THREAD

**Issue by kevinc-cogapp** [kickofftimes/gatsby-template#25]
https://github.com/kickofftimes/gatsby-template/blob/ea18f173e468d84439dfa4c6abb10d7fa7ed90c3/gatsby-node.js#L67

Nit pick - but maybe code style matters :wink: :+1:

**Comment by si** [comment]
Thanks for raising the issue @kevinc-cogapp. 

It would be great to get the collaboration working on this project with this issue as an example. Could you try again?
